### ISSUE TITLE
createOrReplace not working

### ISSUE THREAD

**Issue by chestarss** [snowdrop/istio-java-api#133]
DestinationRule destinationRule = objectMapper.readValue(yaml, DestinationRule.class);
 Object o = istioClient.inAnyNamespace().v1alpha3DestinationRule().createOrReplace(destinationRule);

java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lio.fabric8.kubernetes.api.model.HasMetadata; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [Lio.fabric8.kubernetes.api.model.HasMetadata; is in unnamed module of loader 'app')

	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.createOrReplace(BaseOperation.java:79)
	at so.dian.zerg.nydus.server.service.k8s.impl.K8sResourceServiceImpl.syncDR(K8sResourceServiceImpl.java:50)

**Comment by metacosm** [comment]
Which version of the API are you using?

**Comment by chestarss** [comment]
> Which version of the API are you using?

1.7.7
