### ISSUE TITLE
istio virtualService getDoneableType is null

### ISSUE THREAD

**Issue by chestarss** [snowdrop/istio-java-api#134]
String yaml = "---\n"
                + "apiVersion: \"networking.istio.io/v1beta1\"\n"
                + "kind: \"VirtualService\"\n"
                + "metadata:\n"
                + "  name: \"golang-demo\"\n"
                + "  namespace: \"dian-stable\"\n"
                + "spec:\n"
                + "  hosts:\n"
                + "  - \"golang-demo\"\n"
                + "  http:\n"
                + "  - route:\n"
                + "    - destination:\n"
                + "        host: \"golang-demo\"\n"
                + "        subset: \"v1\"\n"
                + "      weight: 60\n"
                + "    - destination:\n"
                + "        host: \"golang-demo\"\n"
                + "        subset: \"v2\"\n"
                + "      weight: 40";

client.load(new ByteArrayInputStream(yaml.getBytes())).inNamespace("dian-stable").createOrReplace();

java.lang.NullPointerException
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:86)
	at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:30)
	at me.snowdrop.istio.client.internal.handler.networking.v1beta1.VirtualServiceHandler.replace(VirtualServiceHandler.java:42)
	at me.snowdrop.istio.client.internal.handler.networking.v1beta1.VirtualServiceHandler.replace(VirtualServiceHandler.java:23)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:285)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:66)

**Comment by metacosm** [comment]
Which version of the API are you using?

**Comment by chestarss** [comment]
1.7.7
