### ISSUE TITLE
istio 1.7.7 and  kubernetes-client 5.1.0 , ListOptions Exception

### ISSUE THREAD

**Issue by lishiyao123** [snowdrop/istio-java-api#135]
The version I'm using is

        
        <dependency>
            <groupId>me.snowdrop</groupId>
            <artifactId>istio-client</artifactId>
            <version>1.7.7</version>
        </dependency>

        <dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-client</artifactId>
            <version>5.1.0</version>
        </dependency>

but ,When I try to list virtualService ,something is wrong ;
The code :
istioClient.v1alpha3VirtualService().list(listOptions);

The Exception :
Exception in thread "main" java.lang.NoSuchMethodError: okhttp3.HttpUrl.get(Ljava/lang/String;)Lokhttp3/HttpUrl;
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.fetchListUrl(BaseOperation.java:174)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:677)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:85)

When I looked at the source code, I found that the version in the POM was inconsistent with the decompiled source code

**Comment by FqqCS** [comment]
@metacosm   will u support this?

**Comment by metacosm** [comment]
Please try with version `1.7.7.1`.
