### ISSUE TITLE
Unable to deploy DestinationRule with tls mode set

### ISSUE THREAD

**Issue by geoand** [snowdrop/istio-java-api#38]
Using the `generic-derializer` branch I am unable to deploy:

```
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: spring-boot-istio-routing-service
spec:
  host: spring-boot-istio-routing-service
  trafficPolicy:
    tls:
      mode: DISABLE
  subsets:
    - name: a
      labels:
        version: a
    - name: b
      labels:
        version: b

```

with `istioClient.registerCustomResources(resourceAsStream);`

The stacktrace is:

```
java.lang.IllegalArgumentException: Can not construct instance of me.snowdrop.istio.api.model.v1.networking.TLSmode from String value ("DISABLE"): value not one of declared Enum instance names: [SIMPLE, PASSTHROUGH, MUTUAL]
 at [Source: N/A; line: -1, column: -1] (through reference chain: me.snowdrop.istio.api.model.v1.networking.DestinationRule["trafficPolicy"]->me.snowdrop.istio.api.model.v1.networking.TrafficPolicy["tls"]->me.snowdrop.istio.api.model.v1.networking.TLSSettings["mode"])

	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3530)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3449)
	at me.snowdrop.istio.util.YAML.loadIstioResources(YAML.java:67)
	at me.snowdrop.istio.client.IstioClient.registerCustomResources(IstioClient.java:26)
	at me.snowdrop.istio.client.IstioClient.registerCustomResources(IstioClient.java:39)
	at com.example.SimpleTest.run(SimpleTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of me.snowdrop.istio.api.model.v1.networking.TLSmode from String value ("DISABLE"): value not one of declared Enum instance names: [SIMPLE, PASSTHROUGH, MUTUAL]
 at [Source: N/A; line: -1, column: -1] (through reference chain: me.snowdrop.istio.api.model.v1.networking.DestinationRule["trafficPolicy"]->me.snowdrop.istio.api.model.v1.networking.TrafficPolicy["tls"]->me.snowdrop.istio.api.model.v1.networking.TLSSettings["mode"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:74)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1022)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:96)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3779)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2050)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2547)
	at me.snowdrop.istio.api.internal.IstioDeserializer.getIstioSpec(IstioDeserializer.java:58)
	at me.snowdrop.istio.api.internal.IstioDeserializer.deserialize(IstioDeserializer.java:49)
	at me.snowdrop.istio.api.internal.IstioDeserializer.deserialize(IstioDeserializer.java:25)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3525)
	... 27 more
```

**Comment by metacosm** [comment]
Should be fixed now.

**Comment by geoand** [comment]
Tested the fix and it works
